<?php

return [
    [
        'category_id' => '1',
        "title" => "SpotifyWeb",
        "author" => "Felice D'Arcangelo",
        "creation_date" => "2023-03-22",
        "last_update" => "2023-03-27",
        "collaborators" => "",
        "description" => "clone of spotify",
        "languages" => "HTML - CSS",
        "link_github" => "https://github.com/FeliceDArcangelo/html-css-spotifyweb",
    ],
    [
        'category_id' => '1',
        "title" => "Minefield",
        "author" => "Felice D'Arcangelo",
        "creation_date" => "2023-04-28",
        "last_update" => "2023-04-28",
        "collaborators" => "",
        "description" => "clone of minefield",
        "languages" => "HTML - CSS - JS",
        "link_github" => "https://github.com/FeliceDArcangelo/js-campominato-grid",
    ],
    [
        'category_id' => '1',
        "title" => "Boolzapp",
        "author" => "Felice D'Arcangelo",
        "creation_date" => "2023-05-15",
        "last_update" => "2023-05-15",
        "collaborators" => "",
        "description" => "clone of social",
        "languages" => "HTML - CSS - JS",
        "link_github" => "https://github.com/FeliceDArcangelo/vue-boolzapp",
    ],
    [
        'category_id' => '1',
        "title" => "Boolflix",
        "author" => "Felice D'Arcangelo",
        "creation_date" => "2023-06-3",
        "last_update" => "2023-06-3",
        "collaborators" => "",
        "description" => "clone of netflix",
        "languages" => "HTML - VUE.JS",
        "link_github" => "https://github.com/FeliceDArcangelo/vite-boolflix",
    ],
    [
        'category_id' => '1',
        "title" => "Designer",
        "author" => "Felice D'Arcangelo",
        "creation_date" => "2023-05-29",
        "last_update" => "2023-06-01",
        "collaborators" => "",
        "description" => "clone of football league page",
        "languages" => "HTML - VUE.JS",
        "link_github" => "https://github.com/FeliceDArcangelo/proj-html-vuejs",
    ],
    [
        'category_id' => '2',
        "title" => "Travel Agency",
        "author" => "Felice D'Arcangelo",
        "creation_date" => "2023-07-04",
        "last_update" => "2023-07-04",
        "collaborators" => "Felice D'Arcangelo - Lamberto Neri - Nicola Soggiu - Giulio D'Angelo - Domenico Ferrari",
        "description" => "clone of travel agency",
        "languages" => "PHP - BLADE",
        "link_github" => "https://github.com/FeliceDArcangelo/laravel-boolean",
    ],
    
];